language: ruby
cache:
  bundler: true
sudo: false
branches:
  only: master
env:
  matrix:
    - TASK='assets:precompile' # TODO: in production mode
    - TASK='brakeman'
    - TASK='db:create default'
script: bundle exec rake $TASK
