language: ruby
cache:
  bundler: true
sudo: false
branches:
  only: master
env:
  matrix:
    - TASK=assets:precompile
    - TASK=brakeman
    - TASK='db:create default'
script: bundle exec rake $TASK
